service: order-api

provider:
  name: aws
  runtime: nodejs24.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  environment:
    EVENT_BUS_NAME: default

    ORDERS_TABLE:
      Fn::ImportValue: order-status-table-name-${sls:stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: "*"

        - Effect: Allow
          Action:
            - dynamodb:GetItem
          Resource:
            Fn::ImportValue: order-status-table-arn-${sls:stage}

functions:
  createOrder:
    handler: src/handlers/create-order.handler
    events:
      - httpApi:
          path: /orders
          method: post

  getOrder:
    handler: src/handlers/get-order.handler
    events:
      - httpApi:
          path: /orders/{id}
          method: get