service: order-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

  environment:
    EVENT_BUS_NAME: default

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: "*"

functions:
  createOrder:
    handler: src/handlers/create-order.handler
    events:
      - httpApi:
          path: /orders
          method: post